### ISSUE TITLE
Unable to download model weights

### ISSUE THREAD

**Issue by woojeongjin** [lovhag/measure-visual-commonsense-knowledge#1]
Hi! I'd like to download model weights and test the models but I can't access the link.
Could you share the weights?

Thanks!

**Comment by lovhag** [comment]
Hi!
Oh yes, sorry about that and thank you for letting me know! The service my university provides for sharing files only generates sharing links with an expiry time of 30 days..

I updated the link now, so you should be able to access the weights: https://chalmers-my.sharepoint.com/:f:/g/personal/lovhag_chalmers_se/ErO_VM7bO5FHlq0EkVJzLMsBxVwysfIjGPyqf-pqOU9LoQ?e=XfTyMc

Please let me know if it doesn't work, or if something else seems strange!

**Comment by woojeongjin** [comment]
Hi Thanks for the link! It works! 
Do you have a direct download link so I can download them on my server?
Thanks!

**Comment by lovhag** [comment]
Great! 

That is a good question, and something I probably should support.

It doesn't seems as though the cloud storage solution chosen by my university (OneDrive) can be used for this. So I need to look into (and learn about) alternative solutions. Meaning that it might take some time for me to create a direct download link. 

I would recommend using your own manual solution if you need the weights immediately. Otherwise, I will be working on it and can get back to you once it's done!

Do you maybe have any recommendations on suitable solutions for storing and creating direct download links for model weights?

**Comment by lovhag** [comment]
Ok! Now I have put the model weights under a public Huggingface repo (https://huggingface.co/Lo/measure-visual-commonsense-knowledge-model-weights). 

You should be able to download them with e.g. wget by using the link provided under the "Download" button for each model weight file.

Please let me know if it works :)

**Comment by woojeongjin** [comment]
Thanks so much! It works!!
